language: node_js

node_js:
  - stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git config --global user.email "naomiaro@gmail.com"
  - git config --global user.name "naomiaro"

install:
  - npm install

script:
  - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/report-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js"