language: node_js

node_js:
  - stable

before_install:
  - git config --global user.email "travis@dev"
  - git config --global user.name "Travis"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/report-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js"